// Cheatsheets — quick reference pages.
// Each cheatsheet = an array of { heading, rows: [[code, desc], ...] }

const CHEATSHEETS = [
  {
    id: 'js',
    title: 'JavaScript',
    desc: 'The essential syntax you will use every day.',
    color: 'var(--c-foundation)',
    sections: [
      { heading: 'Variables & types', rows: [
        ['let x = 5', 'Mutable variable'],
        ['const x = 5', 'Constant — preferred default'],
        ['typeof x', 'Returns the type as a string'],
        ['Number, String, Boolean', 'Primitive types'],
        ['null, undefined', '"No value" markers'],
        ['Array.isArray(x)', 'Check if value is an array'],
      ]},
      { heading: 'Operators', rows: [
        ['===  /  !==', 'Strict equality (USE THIS)'],
        ['==  /  !=', 'Loose (with type coercion) — avoid'],
        ['&&  ||  !', 'Logical AND, OR, NOT'],
        ['??', 'Nullish coalescing (default if null/undefined)'],
        ['?.', 'Optional chaining: a?.b is undefined if a is null'],
        ['...arr', 'Spread an array into args or another array'],
      ]},
      { heading: 'Strings', rows: [
        ['`hi ${name}`', 'Template literal with interpolation'],
        ['s.length', 'Number of characters'],
        ['s.toUpperCase() / .toLowerCase()', 'Case conversion'],
        ['s.includes(sub)', 'true if contains substring'],
        ['s.split(",")', 'Break into array'],
        ['arr.join("-")', 'Join array into string'],
      ]},
      { heading: 'Arrays', rows: [
        ['arr.push(x) / .pop()', 'Add to / remove from end'],
        ['arr.shift() / .unshift(x)', 'Remove from / add to front'],
        ['arr.map(fn)', 'Transform each — returns new array'],
        ['arr.filter(fn)', 'Keep matching — returns new array'],
        ['arr.reduce(fn, init)', 'Combine into single value'],
        ['arr.find(fn)', 'First matching item'],
        ['arr.some(fn) / arr.every(fn)', 'Any / all match the predicate'],
        ['arr.sort((a,b) => a - b)', 'Sort numerically (ascending)'],
        ['arr.slice(1, 3)', 'Returns sub-array (non-mutating)'],
      ]},
      { heading: 'Objects', rows: [
        ['Object.keys(obj)', 'Array of property names'],
        ['Object.values(obj)', 'Array of values'],
        ['Object.entries(obj)', 'Array of [key, value] pairs'],
        ['{ ...a, ...b }', 'Merge two objects (b wins on conflict)'],
        ['const { name, age } = user', 'Destructuring'],
      ]},
      { heading: 'Async', rows: [
        ['async function f() {}', 'Declares an async function'],
        ['await promise', 'Waits inside async function'],
        ['try { ... } catch (e) {}', 'Handle errors (incl. await)'],
        ['Promise.all([p1, p2])', 'Wait for many in parallel'],
        ['fetch(url).then(r => r.json())', 'Promise-style HTTP'],
      ]},
    ],
  },

  {
    id: 'http',
    title: 'HTTP & REST',
    desc: 'Methods, status codes, and conventions.',
    color: 'var(--c-system)',
    sections: [
      { heading: 'HTTP methods', rows: [
        ['GET /users', 'List or read — no side effects'],
        ['GET /users/5', 'Read one resource'],
        ['POST /users', 'Create a new resource'],
        ['PUT /users/5', 'Replace entire resource'],
        ['PATCH /users/5', 'Update some fields of a resource'],
        ['DELETE /users/5', 'Remove the resource'],
      ]},
      { heading: '2xx Success', rows: [
        ['200 OK', 'Standard success'],
        ['201 Created', 'New resource was created (POST)'],
        ['204 No Content', 'Success but no body to return'],
      ]},
      { heading: '3xx Redirect', rows: [
        ['301 Moved Permanently', 'URL changed forever'],
        ['302 Found', 'Temporary redirect'],
        ['304 Not Modified', 'Cached version is still valid'],
      ]},
      { heading: '4xx Client errors', rows: [
        ['400 Bad Request', 'Malformed request'],
        ['401 Unauthorized', 'Not authenticated'],
        ['403 Forbidden', 'Authenticated but not allowed'],
        ['404 Not Found', 'Resource doesn\'t exist'],
        ['409 Conflict', 'Conflict with current state (e.g. duplicate)'],
        ['429 Too Many Requests', 'Rate-limited'],
      ]},
      { heading: '5xx Server errors', rows: [
        ['500 Internal Server Error', 'Unhandled exception on the server'],
        ['502 Bad Gateway', 'Upstream server returned invalid response'],
        ['503 Service Unavailable', 'Server overloaded or down for maintenance'],
        ['504 Gateway Timeout', 'Upstream server didn\'t respond in time'],
      ]},
      { heading: 'Common headers', rows: [
        ['Content-Type: application/json', 'Body format'],
        ['Authorization: Bearer <token>', 'Auth credential'],
        ['Cache-Control: no-cache', 'Caching directives'],
        ['Cookie: session=abc', 'Auto-sent by browser'],
        ['CORS: Access-Control-Allow-Origin', 'Cross-origin permission'],
      ]},
    ],
  },

  {
    id: 'sql',
    title: 'SQL',
    desc: 'The 90% of SQL you will actually use.',
    color: 'var(--c-cloud)',
    sections: [
      { heading: 'Reading data', rows: [
        ['SELECT * FROM users', 'All columns, all rows'],
        ['SELECT name, email FROM users', 'Specific columns'],
        ['WHERE age > 18', 'Filter rows'],
        ['WHERE name LIKE "A%"', 'Pattern match (%=any chars)'],
        ['ORDER BY created_at DESC', 'Sort (DESC = descending)'],
        ['LIMIT 10 OFFSET 20', 'Pagination'],
        ['SELECT COUNT(*) FROM users', 'Aggregate: count rows'],
        ['GROUP BY country', 'Group + aggregate per group'],
        ['HAVING COUNT(*) > 5', 'Filter on aggregate result'],
      ]},
      { heading: 'Writing data', rows: [
        ['INSERT INTO users (name, email) VALUES (\'A\', \'a@x.com\')', 'Add a row'],
        ['UPDATE users SET name = \'X\' WHERE id = 1', 'Modify rows'],
        ['DELETE FROM users WHERE id = 1', 'Remove rows'],
        ['BEGIN; ... COMMIT;', 'Transaction (all-or-nothing)'],
        ['ROLLBACK', 'Undo current transaction'],
      ]},
      { heading: 'Joins (combine tables)', rows: [
        ['INNER JOIN', 'Only rows that match in both tables'],
        ['LEFT JOIN', 'All from left + matching from right (NULLs if none)'],
        ['RIGHT JOIN', 'Mirror of LEFT'],
        ['FULL OUTER JOIN', 'All rows from both, matched where possible'],
        ['SELECT u.name, p.title FROM users u JOIN posts p ON p.user_id = u.id', 'Typical join syntax'],
      ]},
      { heading: 'Schema (DDL)', rows: [
        ['CREATE TABLE users (id SERIAL PRIMARY KEY, name TEXT)', 'Create a table'],
        ['ALTER TABLE users ADD COLUMN age INT', 'Add column'],
        ['DROP TABLE users', 'Delete table (be careful)'],
        ['CREATE INDEX idx_email ON users (email)', 'Index for fast lookup'],
        ['REFERENCES users(id) ON DELETE CASCADE', 'Foreign key with cascade delete'],
      ]},
    ],
  },

  {
    id: 'git',
    title: 'Git',
    desc: 'Daily commands every developer must know.',
    color: 'var(--c-positioning)',
    sections: [
      { heading: 'Basic workflow', rows: [
        ['git init', 'Start a new repo in current folder'],
        ['git clone <url>', 'Copy a remote repo locally'],
        ['git status', 'See what changed'],
        ['git add <file>', 'Stage a file'],
        ['git add .', 'Stage everything'],
        ['git commit -m "msg"', 'Save staged changes'],
        ['git push', 'Upload to remote'],
        ['git pull', 'Download + merge from remote'],
        ['git fetch', 'Download but don\'t merge'],
      ]},
      { heading: 'Branches', rows: [
        ['git branch', 'List branches'],
        ['git checkout -b new-feature', 'Create + switch to new branch'],
        ['git checkout main', 'Switch branch'],
        ['git switch main', 'Modern alias for checkout'],
        ['git merge feature-x', 'Merge feature-x into current branch'],
        ['git branch -d old-branch', 'Delete merged branch'],
      ]},
      { heading: 'History & inspection', rows: [
        ['git log --oneline', 'Compact commit history'],
        ['git log --graph --all', 'Visual branch graph'],
        ['git diff', 'Unstaged changes'],
        ['git diff --staged', 'Staged changes'],
        ['git show <hash>', 'See a specific commit'],
        ['git blame <file>', 'Who changed each line'],
      ]},
      { heading: 'Undo (carefully)', rows: [
        ['git restore <file>', 'Discard unstaged changes in file'],
        ['git restore --staged <file>', 'Unstage a file'],
        ['git commit --amend', 'Edit the last commit'],
        ['git reset --soft HEAD~1', 'Undo last commit, keep changes staged'],
        ['git reset --hard HEAD~1', '⚠ Erase last commit AND its changes'],
        ['git revert <hash>', 'Make a new commit that undoes another'],
      ]},
    ],
  },

  {
    id: 'docker',
    title: 'Docker',
    desc: 'Build, run, and manage containers.',
    color: 'var(--c-architecture)',
    sections: [
      { heading: 'Images & containers', rows: [
        ['docker build -t my-app .', 'Build an image from Dockerfile'],
        ['docker run my-app', 'Start a container'],
        ['docker run -d my-app', 'Detached (background)'],
        ['docker run -p 3000:3000 my-app', 'Map port host:container'],
        ['docker run -e KEY=val my-app', 'Environment variable'],
        ['docker run -v $PWD:/app my-app', 'Mount a volume (host:container)'],
        ['docker ps', 'List running containers'],
        ['docker ps -a', 'Include stopped'],
        ['docker stop <id>', 'Stop a container'],
        ['docker logs <id>', 'View its logs'],
        ['docker exec -it <id> bash', 'Open a shell inside it'],
      ]},
      { heading: 'Cleanup', rows: [
        ['docker rm <id>', 'Remove a stopped container'],
        ['docker rmi <image>', 'Remove an image'],
        ['docker system prune', '⚠ Remove all unused stuff'],
      ]},
      { heading: 'Dockerfile basics', rows: [
        ['FROM node:20', 'Start from a base image'],
        ['WORKDIR /app', 'Set working directory inside container'],
        ['COPY package*.json ./', 'Copy files in (cache-friendly first)'],
        ['RUN npm install', 'Run a command at build time'],
        ['EXPOSE 3000', 'Document the port (informational)'],
        ['CMD ["node", "server.js"]', 'Default command at run time'],
      ]},
      { heading: 'docker-compose', rows: [
        ['docker compose up', 'Start all services in compose file'],
        ['docker compose up -d', 'Detached'],
        ['docker compose down', 'Stop and remove'],
        ['docker compose logs -f api', 'Follow logs of one service'],
      ]},
    ],
  },

  {
    id: 'sysdesign',
    title: 'System Design',
    desc: 'Patterns and trade-offs to know cold.',
    color: 'var(--c-roles)',
    sections: [
      { heading: 'Latency numbers (memorize)', rows: [
        ['L1 cache', '~1 ns'],
        ['RAM access', '~100 ns'],
        ['SSD random read', '~150 µs'],
        ['Round trip same datacenter', '~500 µs'],
        ['Round trip cross-continent', '~150 ms'],
      ]},
      { heading: 'Scaling moves (in order)', rows: [
        ['1. Add a CDN', 'Serve static files at the edge'],
        ['2. Add a cache (Redis)', 'Absorb read traffic from DB'],
        ['3. Add DB read replicas', 'Scale reads horizontally'],
        ['4. Add a queue (SQS, Kafka)', 'Push slow work off the request path'],
        ['5. Shard the database', 'Split data across DBs (last resort)'],
      ]},
      { heading: 'Caching strategies', rows: [
        ['Cache-aside (lazy)', 'App reads cache → on miss, hit DB then populate cache. Most common.'],
        ['Write-through', 'Every write goes to cache + DB. Slower writes, consistent reads.'],
        ['Write-behind', 'Write to cache; flush to DB asynchronously. Fast but can lose data.'],
        ['TTL', 'Auto-expire after N seconds — accept some staleness.'],
      ]},
      { heading: 'CAP theorem', rows: [
        ['Consistency', 'All nodes see the same data at the same time'],
        ['Availability', 'Every request gets a response (no downtime)'],
        ['Partition tolerance', 'Works despite network failures between nodes'],
        ['Real systems', 'Pick C+P (e.g. Postgres) or A+P (e.g. DynamoDB). You can\'t have all 3.'],
      ]},
    ],
  },
];

window.CHEATSHEETS = CHEATSHEETS;
